import type { Projeto } from "../types/projeto";

export const projetosMock: Projeto[] = [
  {
    id: "1",
    titulo: "Horta Inteligente com Sensores IoT",
    descricao:
      "Sistema automatizado de irrigação usando sensores de umidade e Arduino, reduzindo o desperdício de água em cultivos escolares através de monitoramento em tempo real.",
    equipe: ["Ana Silva", "Bruno Costa", "Carla Mendes"],
    eixoTematico: "Sustentabilidade",
    evento: "Sectec 6",
    curso: "Informática",
    bannerUrl: "/banners/banner-modelo-jopar.png",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: "2",
    titulo: "App de Reciclagem Comunitária",
    descricao:
      "Aplicativo mobile que conecta moradores a pontos de coleta seletiva próximos, com sistema de pontuação e recompensas por reciclagem.",
    equipe: ["Diego Santos", "Elisa Rocha"],
    eixoTematico: "Meio Ambiente",
    evento: "Sectec 6",
    curso: "Desenvolvimento de Sistemas",
    bannerUrl: "https://placehold.co/600x400/16a34a/ffffff?text=App+Reciclagem",
    videoUrl: null,
  },
  {
    id: "3",
    titulo: "Robô Seguidor de Linha para Ensino",
    descricao:
      "Kit educacional de robótica de baixo custo para introduzir conceitos de programação e eletrônica em escolas públicas.",
    equipe: ["Felipe Araújo", "Gabriela Lima", "Hugo Pereira"],
    eixoTematico: "Robótica",
    evento: "Sectec 5",
    curso: "Eletrônica",
    bannerUrl: "https://placehold.co/600x400/16a34a/ffffff?text=Robo+Seguidor",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: "4",
    titulo: "Plataforma de Apoio Psicológico Estudantil",
    descricao:
      "Sistema web para agendamento de atendimentos e conteúdos de saúde mental voltados a estudantes do ensino técnico.",
    equipe: ["Isabela Torres"],
    eixoTematico: "Saúde",
    evento: "Sectec 6",
    curso: "Informática",
    bannerUrl: "https://placehold.co/600x400/16a34a/ffffff?text=Apoio+Psicologico",
    videoUrl: null,
  },
  {
    id: "5",
    titulo: "Monitoramento de Qualidade do Ar",
    descricao:
      "Estação de baixo custo com sensores de CO2 e partículas finas, exibindo dados em um painel público para conscientização ambiental.",
    equipe: ["João Pedro", "Karina Alves"],
    eixoTematico: "Meio Ambiente",
    evento: "Sectec 5",
    curso: "Eletrônica",
    bannerUrl: "https://placehold.co/600x400/16a34a/ffffff?text=Qualidade+do+Ar",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: "6",
    titulo: "Sistema de Gestão de Biblioteca Escolar",
    descricao:
      "Ferramenta para controle de empréstimos, reservas e acervo, com relatórios automáticos para bibliotecários.",
    equipe: ["Larissa Nunes", "Marcos Vieira"],
    eixoTematico: "Educação",
    evento: "Sectec 6",
    curso: "Desenvolvimento de Sistemas",
    bannerUrl: "https://placehold.co/600x400/16a34a/ffffff?text=Gestao+Biblioteca",
    videoUrl: null,
  },
  {
    id: "7",
    titulo: "Braço Robótico para Triagem de Recicláveis",
    descricao:
      "Protótipo com visão computacional para identificar e separar plástico, vidro e metal automaticamente.",
    equipe: ["Natália Farias", "Otávio Ramos", "Paula Duarte"],
    eixoTematico: "Robótica",
    evento: "Sectec 4",
    curso: "Eletrônica",
    bannerUrl: "https://placehold.co/600x400/16a34a/ffffff?text=Braco+Robotico",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: "8",
    titulo: "Chatbot de Orientação Vocacional",
    descricao:
      "Assistente virtual que ajuda estudantes do ensino médio a explorar cursos técnicos com base em interesses e habilidades.",
    equipe: ["Rafael Souza"],
    eixoTematico: "Educação",
    evento: "Sectec 6",
    curso: "Informática",
    bannerUrl: "https://placehold.co/600x400/16a34a/ffffff?text=Chatbot+Vocacional",
    videoUrl: null,
  },
  {
    id: "9",
    titulo: "Painel Solar de Baixo Custo para Comunidades Rurais",
    descricao:
      "Protótipo de captação de energia solar com materiais reaproveitados, voltado para famílias sem acesso à rede elétrica.",
    equipe: ["Sabrina Costa", "Thiago Martins"],
    eixoTematico: "Sustentabilidade",
    evento: "Sectec 5",
    curso: "Eletrônica",
    bannerUrl: "https://placehold.co/600x400/16a34a/ffffff?text=Painel+Solar",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: "10",
    titulo: "App de Caronas Solidárias entre Alunos",
    descricao:
      "Aplicativo que conecta estudantes que fazem trajetos parecidos até a escola, reduzindo custo e emissão de carbono.",
    equipe: ["Ursula Pinto", "Victor Hugo"],
    eixoTematico: "Meio Ambiente",
    evento: "Sectec 6",
    curso: "Desenvolvimento de Sistemas",
    bannerUrl: "https://placehold.co/600x400/16a34a/ffffff?text=Caronas+Solidarias",
    videoUrl: null,
  },
  {
    id: "11",
    titulo: "Exoesqueleto de Mão para Reabilitação",
    descricao:
      "Dispositivo assistivo de baixo custo impresso em 3D para auxiliar pacientes em recuperação motora das mãos.",
    equipe: ["Wesley Barros", "Yasmin Rocha"],
    eixoTematico: "Saúde",
    evento: "Sectec 4",
    curso: "Eletrônica",
    bannerUrl: "https://placehold.co/600x400/16a34a/ffffff?text=Exoesqueleto",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: "12",
    titulo: "Plataforma de Doação de Materiais Escolares",
    descricao:
      "Sistema que conecta doadores de material escolar a alunos em situação de vulnerabilidade dentro da própria instituição.",
    equipe: ["Zoé Almeida"],
    eixoTematico: "Educação",
    evento: "Sectec 5",
    curso: "Informática",
    bannerUrl: "https://placehold.co/600x400/16a34a/ffffff?text=Doacao+Material",
    videoUrl: null,
  },
  {
    id: "13",
    titulo: "Estufa Automatizada com Controle de Clima",
    descricao:
      "Estufa com controle automático de temperatura, umidade e luminosidade para otimizar o cultivo de hortaliças.",
    equipe: ["Alan Freitas", "Bianca Ribeiro"],
    eixoTematico: "Sustentabilidade",
    evento: "Sectec 6",
    curso: "Eletrônica",
    bannerUrl: "https://placehold.co/600x400/16a34a/ffffff?text=Estufa+Automatizada",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: "14",
    titulo: "Jogo Educativo sobre Primeiros Socorros",
    descricao:
      "Jogo digital interativo que ensina procedimentos básicos de primeiros socorros para adolescentes de forma lúdica.",
    equipe: ["Caio Nogueira", "Débora Sales"],
    eixoTematico: "Saúde",
    evento: "Sectec 6",
    curso: "Desenvolvimento de Sistemas",
    bannerUrl: "https://placehold.co/600x400/16a34a/ffffff?text=Jogo+Primeiros+Socorros",
    videoUrl: null,
  },
];